package rs.raf.word_distribution.events;

public enum EventType {
    READING_STARTED, READING_FINISHED,

    CRUNCHER_STARTED, CRUNCHER_FINISHED,

    OUTPUT_STORED_CRUNCHER_DATA_FRAME, OUTPUT_GAINED_ACCESS_TO_CRUNCHER_DATA_FRAME,


    OUT_OF_MEMORY
}
