package rs.raf.word_distribution.events;

public enum EventType {
    READING_STARTED, READING_FINISHED,
    CRUNCHER_STARTED, CRUNCHER_FINISHED,
    STORED_CRUNCHER_DATA_FRAME, AGGREGATION_FINISHED,

    OUT_OF_MEMORY
}
